apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  name: awx-restore-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: awx-restore-role
subjects:
- kind: ServiceAccount
  name: awx-operator-controller-manager
  namespace: awx-restore
