---
# Source: awx-operator/templates/clusterrolebinding-awx-operator-proxy-rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    helm.sh/chart: awx-operator
  name: awx-operator-proxy-rolebinding-awx-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: awx-operator-proxy-role-awx-operator
subjects:
  - kind: ServiceAccount
    name: awx-operator-controller-manager
    namespace: 'default'
