---
apiVersion: awx.ansible.com/v1beta1
kind: AWXRestore
metadata:
  name: awx-restore
  namespace: awx
spec:
  deployment_name: awx
  backup_name: awxbackup
  backup_pvc: awx-backup-claim
  backup_pvc_namespace: awx

